# The location of the bag file to replay. This can accept environment args (ex. $(optenv HOME))
bag_file: "$(optenv HOME)/Desktop/bag-test.bag"
# The rate at which to step through the bag file, in seconds.
simulated_rate: 0.1
# The frame_id of the camera as represented in the TF tree.
camera_frame_id: "infrastructure/camera/base_link"
# The global static frame used to reference all models in Gazebo. Almost always 'map'.
global_frame: "map"

# Specify values needed by any data writing format.
yolo:
    output_folder: "$(optenv HOME)/Desktop/output"

# The list of robots to control.
/robot_list: ["athreos", "ephara"]

# Specify the needed values for each robot.
athreos:
    class: 15
    id: 7
    frame_id: "base_link"
    # These are the key points to look for in detection, relative to the origin of the
    # frame specified in "frame_id"
    keypoints: [[0.35, -0.3, 0.0], [0.35, 0.3, 0.0], [-0.4, 0.3, 0.0], [-0.4, -0.3, 0.0]]

ephara:
    class: 15
    id: 2
    frame_id: "base_link"
    # These are the key points to look for in detection, relative to the origin of the
    # frame specified in "frame_id"
    keypoints: [[0.35, -0.3, 0.0], [0.35, 0.3, 0.0], [-0.4, 0.3, 0.0], [-0.4, -0.3, 0.0]]